fix

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -21,7 +21,7 @@ concurrency:
 defaults:
   run:
     shell: bash
-    working-directory: terraform
+    working-directory: terraform/env
 
 permissions: {}
 
@@ -54,20 +54,23 @@ jobs:
       - uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: ${{ env.TERRAFORM_VERSION }}
-      - id: fmt
-        run: terraform fmt -recursive -check
-        continue-on-error: true
+      # - id: fmt
+      #   run: terraform fmt -recursive -check
+      #   continue-on-error: true
       - id: init
         run: terraform init
       - id: validate
         run: terraform validate -no-color
       - id: plan
-        run: |
-          set -x
-          terraform plan -no-color
-        continue-on-error: true
-      - if: steps.plan.outcome == 'failure'
-        run: exit 1
+        run: terraform plan -no-color
+        # continue-on-error: true
+
+      # - run: echo ${{ steps.plan.outputs.stdout }}
+      # - run: echo ${{ steps.plan.outputs.stderr }}
+      # - run: echo ${{ steps.plan.outputs.exitcode }}
+
+      # - if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
       # - name: Terraform Apply
       #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
